services:

  site:
    container_name: bim4everyone-docs
    
    image: bim4everyone-docs:latest
    build:
      context: .
    command: server
    
    ports:
      - "1313:1313"
    
    volumes:
      - .:/src
